---
blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/AlexandrosAlexiou/kotlin.nvim/discussions/new?category=q-a
    about: Please ask and answer questions here.
  - name: Feature request
    url: https://github.com/AlexandrosAlexiou/kotlin.nvim/discussions/new?category=ideas
    about: Request an enhancement for kotlin.nvim
